** quiet  

[[http://melpa.org/#/quiet][file:http://melpa.org/packages/quiet-badge.svg]]

A simple package to disconnect from the online world for a while, possibly reconnecting later. Any interruptions or distractions which occur once the command is run are guaranteed to be local.

** installation
 
the package can be installed from melpa ~M-x package-install [RET] quiet [RET]~ 

** disconnection

~M-x quiet~ will disconnect from the network, optionally reconnecting after a certain time.

the function ~quiet~ can be used anywhere in emacs where a lack of network access could be seen as a feature, e.g.  as a mode-hook (or with ~defadvice~) to your preferred distraction free writing environment. 

** reconnection

 ~M-x quiet-reconnect~ will manually reconnect to the network, however you can enable a timer to automatically reconnect by setting ~quiet-timer~ to a number of minutes. e.g. ~(setq quiet-timer 60)~ will enable ~quiet~ to reconnect after one hour. if  ~quiet-timer~ is set to ~0~ it won't reconnect automatically.

** network interfaces

you may want to ~customize~ or ~setq~ ~quiet-disconnect~ and ~quiet-connect~ to the appropriate shell commands to turn your network (or single interface) on or off.

 - MacOS (current default). ~networksetup -setairportpower airport {on,off}~
 - GNU/Linux. ~ifup wlan0~ and ~ifdown wlan0~
 - *BSD. ~service netif {stop, start}~

** further 

 - [[https://www.worldcat.org/title/flow-the-psychology-of-optimal-experience/oclc/848200090][Mihaly Csikszentmihályi (1990). Flow: The Psychology of Optimal Experience. Harper & Row. ISBN 9780060162535]]
 - [[https://hbr.org/2011/11/the-myth-of-monotasking/][The Myth of Monotasking]].
 
